services:
  - type: web
    name: discord-bot-ia
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -u bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: AI_MODEL
        value: mixtral-8x7b-32768
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
